<?php
define("ERROR_FORMATO_IMAGEN", -1); 
define("ERROR_TAMAÑO_IMAGEN", -2); 
define("ERROR_IMAGEN_MALICIOSA", -3); 
define("ERROR_SUBIDA_IMAGEN", -4); 
define("EFECTIVIDAD_INICIAL", 1); 
define("USUARIO_ARBITRO", 255); 
define("USUARIO_NORMAL", 254); 
define("MINIMO_PAREJAS_TORNEO", 2); 



/* Tamaños de los campos en la BD */ 

define("SIZE_IMG_LOCALIZACION_CARGADOR", 50);

define("SIZE_NOTIF_TIPO", 1); 
define("SIZE_NOTIF_TEXTO", 50); 

define("SIZE_PAREJA_EFECTIVIDAD", 10); 

define("SIZE_PARTIDO_AMISTOSO_NOMBRE", 40); 
define("SIZE_PARTIDO_FECHA_INICIO", 20); 
define("SIZE_PARTIDO_FECHA_INSCRIPCION", 20); 
define("SIZE_PARTIDO_RESULTADOS", 40); 
define("SIZE_PARTIDO_HORA", 10); 
define("SIZE_PARTIDO_AMISTOSO_CIUDAD", 40); 
define("SIZE_PARTIDO_AMISTOSO_DIRECCION", 40); 

define("SIZE_PARTIDO_TORNEO_NOMBRE", 40); 
define("SIZE_PARTIDO_TORNEO_RESULTADOS", 40); 
define("SIZE_PARTIDO_TORNEO_FECHA_INICIO", 20); 
define("SIZE_PARTIDO_TORNEO_HORA", 10); 

define("SIZE_TORNEO_NOMBRE", 40); 
define("SIZE_TORNEO_EFECTIVIDAD_REQUERIDA", 10); 
define("SIZE_TORNEO_PREMIO", 40); 
define("SIZE_TORNEO_DIRECCION", 40); 
define("SIZE_TORNEO_CIUDAD", 40); 
define("SIZE_TORNEO_FECHA_INICIO", 20); 
define("SIZE_TORNEO_FECHA_FIN", 20); 
define("SIZE_TORNEO_FECHA_INSCRIPCION", 20); 
define("SIZE_TORNEO_MAX_PAREJAS", 3); 

define("SIZE_USUARIO_EMAIL", 30); 
define("SIZE_USUARIO_NOMBRE", 20); 
define("SIZE_USUARIO_APELLIDO1", 25); 
define("SIZE_USUARIO_APELLIDO2", 25); 
define("SIZE_USUARIO_EFECTIVIDAD", 8); 
define("SIZE_USUARIO_PASSWORD", 256); 
define("SIZE_USUARIO_PROVINCIA", 30); 
define("SIZE_USUARIO_LOCALIDAD", 30); 
define("SIZE_USUARIO_SEXO", 10); 
define("SIZE_USUARIO_PERFIL", 50); 

/* TIPOS DE NOTIFICACIONES */ 

define("NOTIFICACION_SOLICITUD_PAREJA", 1); 
define("NOTIFICACION_RECHAZO_PAREJA", 2); 
define("NOTIFICACION_ACEPTO_PAREJA", 3); 
define("NOTIFICACION_DESAPUNTADO_TORNEO", 4);
define("NOTIFICACION_PARTIDO_PROXIMO", 5); 


/* SECCIONES DE LA PAGINA */ 

define("SECCION_PERFIL", 1); 
define("SECCION_JUGADOR", 2); 
define("SECCION_TORNEO", 3); 
define("SECCION_PARTIDO", 4);
define("SECCION_INDEX", 5); 
define("SECCION_ACERCA_DE", 6); 
define("SECCION_LOGIN", 7); 
define("SECCION_REGISTRO", 8); 

/* TO_DO CORRECTO POR COMPROBACIONES */ 
define("COMPROBACION_CORRECTA", 1000000); 
define("OPERACION_CORRECTA", 10000);

/* ERRORES EN LA PAGINA */ 

define("ERROR_TORNEO_LLENO", 330);
define("ERROR_EFECTIVIDAD_INSUFICIENTE", 331);
define("ERROR_TORNEO_CERRADO", 332); 
define("ERROR_USUARIO_APUNTADO_TORNEO", 333); 
define("ERROR_USUARIO_NO_LOGEADO", 334); 
define("ERROR_APLICACION", 3347);
define("ERROR_USUARIO_REPETIDO", 335);
define("ERROR_PASSWORD_INCORRECTO", 336);
define("ERROR_USUARIO_PENDIENTE_ACEPTACION_TORNEO", 337); 
define("ERROR_USUARIO_PENDIENTE_ACEPTAR_SOLICITUD_PAREJA", 338);
define("ARBITRO_EDITAR_TORNEO", 339);
define("TEXTO_ERROR_ESTANDAR", "ERROR EN TU SOLICITUD: Estamos teniendo problemas vuelve a intentarlo mas tarde. ");
define("TEXTO_ERROR_GRAVE", "ERROR GENERAL de Padel2u, espere un tiempo a que los administradores arreglen la BD. Sentimos todas las molestias que esto le pueda causar. ");





define("PAREJA_FANTASMA", -100000); // Usado un numero negativo para prevenir colisiones con Ids de usuarios. 

define("OPERACION_DATOS_TORNEO", 1); 
define("OPERACION_PARTIDOS_TORNEO_SIN_FILTRO", 2);
define("OPERACION_UBICACION_TORNEO", 3);
define("OPERACION_INSCRITOS_TORNEO", 4); 
define("OPERACION_PARTIDO_TORNEO", 5);
define("OPERACION_DATOS_USUARIO_Y_ESTADISTICAS", 1); 
define("OPERACION_NOTIFICACIONES_USUARIO", 2); 
define("OPERACION_BORRAR_NOTIFICACION", 3); 
define("OPERACION_COMPROBAR_EMAIL_USUARIO", 4); 
define("OPERACION_COMPROBAR_PASSWORD_USUARIO", 5); 






